---
    version: "3.8"
    services:
      nginx:
        image: nginx
        container_name: nginx
        volumes:
         - ./templates:/etc/nginx/templates
         - ./webpage:/webpage
        ports:
          - 80:80
          - 8080:8080
        networks:
          - engine
        
    
    
      nginx-exporter:
        image: nginx/nginx-prometheus-exporter
        container_name: nginx-exporter
        user: root
        environment: 
          - SCRAPE_URI=http://nginx:8080/stub_status
          - NGINXRETRIES=10
        restart: always
        ports:
          - 9113:9113
        networks:
          - engine
        depends_on:
          - nginx
    
    networks:
      engine:
        driver: bridge