version: "3.2"
networks:
  engine2:
    driver: bridge
services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

    ports:
      - 9091:9090
    networks:
      - engine2


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
     - engine2
    volumes:
     - ./grafana/grafana.ini:/etc/grafana/grafana.ini