global:
  scrape_interval: 10s
  scrape_timeout: 10s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']