global:
  scrape_interval: 10s
  scrape_timeout: 10s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'nginx'
    static_configs:
      - targets: ['192.168.1.87:9113']
  - job_name: 'node'
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/node_exporter.crt
      insecure_skip_verify: true
    static_configs:
    - targets: ['192.168.1.87:9100']
